### ISSUE TITLE
CORS Allow Origin '*' not working

### ISSUE THREAD

**Issue by ykbks** [fruitcake/laravel-cors#317]
Hi there. Thank you for the amazing and useful class. I am facing a weird issue.

Here's my setup:

1) Laravel API [cors]
2) Angular app (diff domain, works with API)
3) VueJS app (diff domain, getting errors).

My CORS config is the same as the default setup:

```
'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedOriginsPatterns' => [],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
```

I ran `php artisan passport:install` a few times but that didn't solve the issue.

I have just 1route that this is not working with:
```
Route::group(['prefix' => 'v1'], function()
{
    Route::get('questionnaire', 'PreRegistration@sendQuestionnaire'); // works
    Route::post('questionnaire', 'PreRegistration@getAnswers'); // doesn't work
});
Route::post('login', ['as' => 'user.login', 'uses' => 'API\AuthController@login']);  // works
Route::post('register', ['as' => 'user.register', 'uses' => 'API\AuthController@register']); // works
Route::post('activate', ['as' => 'user.activate', 'uses' => 'API\AuthController@activate']); //works 
```

The code is basically the same, I can have anything in there, but that one route will not work from the 3rd location (VueJS app)

error:
![error](https://i.imgur.com/uHYGDB8.png)

**Comment by cmpere** [comment]
Hi, i have the same config, 
```
 'supportsCredentials'    => false,
    'allowedOrigins'         => ['*'],
    'allowedOriginsPatterns' => [],
    'allowedHeaders'         => ['*'],
    'allowedMethods'         => ['*'],
    'exposedHeaders'         => [],
    'maxAge'                 => 0,
```
only \Barryvdh\Cors\HandleCors::class is in the global array.

```
/**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Barryvdh\Cors\HandleCors::class
    ];
```
and still getting this:

![captura de pantalla 2018-07-31 a la s 23 03 49](https://user-images.githubusercontent.com/4393094/43500541-bcbce97a-9516-11e8-80f0-aa24b1236d47.png)

Server 1
 Backend: Laravel 5.6 with "barryvdh/laravel-cors": "^0.11.0",

Server 2
Vuejs, axios

```
export default Base.extend({
    data() {
        return {
            payload: {
                email: null,
                password: null,
                password_confirmation: null,
                type: 'ecommerce'
            }
        }
    },
    methods: {
        register() {
            axios.post(this.api.register, this.payload)
                .then(response => console.log('Response', response))
                .catch(({response}) => {
                    this.errors = _.mapValues(response.data.errors, (itm) => itm[0])
                })
        }
    }
})
```
i did some research but, in order to get the things done and later fix this, you can bypass the package and add the headers manually at the top of your route file (api.php or web.php)

bypass
```
 "extra": {
        "laravel": {
            "dont-discover": [
                 "barryvdh/laravel-cors"
            ]
        }
    },
```
then `composer dump-autoload`

routes (api.php for me)
```
header("Access-Control-Allow-Origin: *");
header('Access-Control-Allow-Methods: POST,GET,PUT,PATCH,OPTIONS');
header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept');
``` 
Yeah, looks ugly. 

well, i'm still digging on this :/

**Comment by tahsin352** [comment]
I got the same problem. i removed csrf token. but still same error. need help... any solution???

**Comment by rkorebrits** [comment]
Same here, completely blank install of Laravel, completed the steps for Laravel with "Global usage" and `vendor:publish`, still getting

    Failed to load http://localhost:8000/api/jobs/get: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

**Comment by lefrankleal** [comment]
+1

**Comment by djhype** [comment]
@cmpere Are you modifying/proxying the request through Laravel? I was experiencing the same issue (the Access-Control-Allow-Origin header being set to an empty string), and it is because the route I was doing this with was proxying the request. Here is what I had in my AuthController:

```
public function login(Request $request)
{
    $this->validateLogin($request);

    if ($this->hasTooManyLoginAttempts($request)) {
        $this->fireLockoutEvent($request);

        return $this->sendLockoutResponse($request);
    }

    $oauthRequest = Request::create('/oauth/token', 'POST', [
        'grant_type' => 'password',
        'client_id' => env('API_CLIENT_ID'),
        'client_secret' => env('API_CLIENT_SECRET'),
        'username' => $request->email,
        'password' => $request->password,
    ]);

    return app()->handle($oauthRequest);
}
```

The issue is that I would return the response based on the `$oauthRequest` instead of the actual request from the browser. I was able to fix this by changing the above to the following:

```
public function login(Request $request)
{
    $this->validateLogin($request);

    if ($this->hasTooManyLoginAttempts($request)) {
        $this->fireLockoutEvent($request);

        return $this->sendLockoutResponse($request);
    }

    $oauthRequest = Request::create('/oauth/token', 'POST', [
        'grant_type' => 'password',
        'client_id' => env('API_CLIENT_ID'),
        'client_secret' => env('API_CLIENT_SECRET'),
        'username' => $request->email,
        'password' => $request->password,
    ]);

    // since we are creating a mock request, set the origin of the mock request to match that of the original
    // request. the logic to determine whether this origin is allowed is handled by the CORS middleware
    $oauthRequest->headers->add(['Origin' => $request->headers->get('Origin')]);

    return app()->handle($oauthRequest);
}
```

I haven't finished testing yet to see if this has any adverse effects, or if there are more CORS related headers that I need to add, but this is now working for my front-end application and I no longer receive any CORS related errors in the browser.

**Comment by spawn-guy** [comment]
thanks @djhype . had the same problem right now.
when you RE-create the request like `app(OAuthPasswordRequest::class)` (for example) the resulting request does miss the `Origin` header. thus `HandleCors` does not get triggered and the resulting response misses CORS-related headers `Access-Control-Allow-Origin` etc.

```
$requestModified = app(OAuthPasswordRequest::class);
$requestModified->headers->add(['Origin' => $request->headers->get('Origin')]);
```
fixes the problem

**Comment by syamsoul** [comment]
i'm using Laravel 5.6...

what is working for me is `composer update`...

and then, poof, my problem is solved....

**Comment by sshiling** [comment]
My problem was that I send request to `login/` instead of `login`.
Works correctly after slash delete.

**Comment by mishazapl** [comment]
$this->app->instance('Asm89\Stack\CorsService', new CorsService(config('cors')));

**Comment by ankgne** [comment]
I was facing this issue while using passport authentication from my angular front end application and resolved it by following below steps:

Adding oauth path as shown below in config/cors.php
`'paths' => ['api/*', 'oauth/*'],`
Using below values in AuthServiceProvider.php
`Passport::routes(null, ['middleware' => [ \Fruitcake\Cors\HandleCors::class ]]);`
instead of
`Passport::routes();`
Refreshing the config cache
php artisan config:clear
