### ISSUE TITLE
Middleware should only set headers instead of returning 403 error

### ISSUE THREAD

**Issue by renspoesse** [fruitcake/laravel-cors#354]
The HandleCors middleware of this package I believe incorrectly returns a 403 response if an Origin is not matched to the allowed origins config.

A quick look at the specification (https://www.w3.org/TR/cors/) does not mention anything like this. Instead, the Access-Control-Allow-Origin should be added with a value specifying the origin that is allowed or no additional headers should be set at all.

[Koa](https://github.com/koajs/cors/blob/master/index.js) and [Express](https://github.com/expressjs/cors/blob/master/lib/index.js) middlewares seem to implement this correctly. That is, they never block execution of the next middleware.

Right now the CORS middleware also affects server-to-server communication (only if the server sets an Origin header), whereas the same origin policy is only meant as a protection for web browser requests and it's the browsers that should make the final decision based on the header values. [This post](https://stackoverflow.com/questions/36958999/cors-is-it-a-client-side-thing-a-server-side-thing-or-a-transport-level-thin) also explains it that way.

**Comment by Megadoden** [comment]
> Right now the CORS middleware also affects server-to-server communication
Only if the servers sets an Origin-header. 

But I agree. I've had issues with this and did not expect that the server would validate CORS-requests as I assumed this was the browser's job. Since Chrome sets the Origin-header even on same-origin requests, you might end up having the middleware lock you out in certain cases unless you whitelist your own domain (for example if you expose your application from a load balancer which communicates with the individual hosts in a different HTTP-scheme (e.g. HTTPS terminates at the load balancer). This will trigger HandleCors to believe its a CORS-request since Origin is set and https://mydomain.com !== http://mydoamin.com, and the middleware will fail your front-end requests served from the same domain, when it should've been the browser's job to do so.

**Comment by barryvdh** [comment]
This has been changed in v2 of this library (and stack-cors), the resources are not blocked by the middleware, only headers are added. If you have issues with the current implementation, please let me know. And sorry for the delay.
